config/routes.rb
Hxl::Application.routes.draw do
  resources :pages
  
  resources :exports do
    collection do
      get 'excel_parsing'
    end
  end
  
  resources :imports do
    collection do
      get 'excel'
      get 'web_service'
      post 'parsed_excel'
      get 'get_workbook'
    end
  end

  root :to => 'pages#home'

end

app/models/asset.rb
class Asset < ActiveRecord::Base
  has_attached_file :data
  belongs_to :user
  belongs_to :organization
  belongs_to :project
end

app/models/organization.rb
class Organization < ActiveRecord::Base
  belongs_to :user
  has_many :assets
end

app/models/page.rb
class Page < ActiveRecord::Base
end

app/models/project.rb
class Project < ActiveRecord::Base
  has_many :assets
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :organizations
  has_many :assets
  
  def creating(user_name, organization_name, data)
    # create user if it is not available
    user = User.find({ :name => user_name}) || User.create({ :name => user_name})
    # create org. and user relation if user available
    # create org. if it is available
    org = Organization.find({ :name => organization_name}) || (user.present? ? (Organization.create({ :name => organization_name, :user_id => user }) ) : (Organization.create({ :name => organization_name}) if organization_name.present?))
    (org.present? ? (user.assets << data; org.assets << data) : ( user.assets << data )) if data.present
    return user || org
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/exports_controller.rb
class ExportsController < ApplicationController
  def home;end
  
  def excel;end
  
  def webservice;end
  
  def create
    #if params[:user][:name].blank? and params[:organization][:name].blank?
    if params[:project][:name].blank?
      flash[:notice] = "Please input your project name"
      redirect_to root_path and return
    end
    if params[:data].blank?
      flash[:notice] = "Don't forget to include your file."
      redirect_to root_path and return
    end
    
    #current_user = User.creating(params[:user][:name], params[:organization][:name], params[:data])
    project = Project.create({ :name => params[:project][:name]})
    project.assets.create({:data => params[:data]})
        
    redirect_to export_path({:project_id => project.id})
  end
  
  def show
    @project = Project.find_by_id(params[:project_id]||params[:id])
  end
  
  def excel_parsing
    project = Project.find_by_id(params[:project_id])
    
  end
end

app/controllers/imports_controller.rb
class ImportsController < ApplicationController
  def excel;end
  
  def parsed_excel
    #!need to refactor the code
    @project = Project.find_by_name(params["data"].original_filename) || Project.create({:name => params["data"].original_filename})
    @asset = Asset.find_by_data_file_name(params["data"].original_filename) || Asset.create({:data => params["data"], :project_id => @project.present? ? @project.id : nil})
    asset_data = get_asset_path(@asset)
    Spreadsheet.client_encoding = 'UTF-8'
    @book = Spreadsheet.open("#{Rails.root}/public#{asset_data}")
  end
  
  def get_workbook
    @asset = Asset.find_by_id(params["asset_id"])
    @project = @asset.project
    asset_data = get_asset_path(@asset)
    Spreadsheet.client_encoding = 'UTF-8'
    book = Spreadsheet.open("#{Rails.root}/public#{asset_data}")
    @sheet = book.worksheet params["workbook_index"].to_i
  end
  
  def web_service;end
  
  protected
  
  def get_asset_path(asset)
    asset_data = asset.data.to_s
    asset_data = asset_data.split("?")[0] if asset_data.include?("?")
    asset_data
  end 
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home;end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/exports/show.html.erb
<script>
  $("document").ready(function(){
    $.get("/export/excel_parsing",{"project_id": $(this).attr("id")}, function(respond){
      console.dir(respond);
    });
  });
</script>
<h1>Project Exporter</h1>

<div><%= @project.name %></div>

<br/>

<div>Files:</div>
<% if @project.assets.present? %>
  <div>
    <% @project.assets.each_with_index do |asset, index| %>
      <%= index + 1%>. <%= link_to "#{asset.data.original_filename}", "#", :id => asset.id %>
    <%end%>
  </div>
<% end %>

app/views/imports/excel.html.erb
<div>
  <%= form_tag('/imports/parsed_excel', :multipart => true) do -%>
    <div>
      <%= label_tag "Excel File" %><br/>
      <%= file_field_tag :data %>
    </div>
    <br/> 
    <div><%= submit_tag 'Upload' %></div>
  <% end -%>
</div>

app/views/imports/get_workbook.html.erb
<%= hidden_field_tag "project-name", @project.name %>
<div>
  <%= link_to "Export to HXL", "#", :id => "export-hxl" %>
</div>
<br/>
<table>
  <% @sheet.each_with_index do |row,row_index|  %>
    <tr id="row_<%= row_index  %>" class="<%= cycle("odd", "even") -%>">
      <td><%= check_box_tag "check_list_#{row_index}" if row_index > 0 %></td>
      <% row.each_with_index do |val, column_index| %>
        <td id="row_<%= row_index  %>_column_<%= column_index %>"><%= val.is_a?(Spreadsheet::Formula) ? val.value : val  %></td>
      <%end%>
    </tr>  
  <%end%>
  <table>

app/views/imports/parsed_excel.html.erb
<div>
  <div>    
    <h3><span><%= @project.name %> </span> :: Worksheets</h3>
    <%= hidden_field_tag "project-name", @project.name %>
    <% @book.worksheets.each_with_index do |sheet, workbook_index| %>
      <ul>
        <li> <%= link_to sheet.name, "#worksheet_frame", :onclick=>"$('#worksheet_frame').attr('src', '#{get_workbook_imports_path({:asset_id => @asset.id, :workbook_index => workbook_index })}' )" %> </li>
      </ul>
    <%end%>
  </div>
  <iframe id="worksheet_frame" src=""/>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Hxl</title>
    <%= stylesheet_link_tag    "application", :media => "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <p><%= flash[:notice] if flash[:notice] %></p>
    <%= yield %>

  </body>
</html>

app/views/pages/home.html.erb
<h1> HXL Exporter </h1>
<br/>

<ul id="menu">
  <li><%= link_to "Excel", excel_imports_path %></li>
  <!--<li><#%= link_to "Web Service", web_service_imports_path %></li>-->
</ul>
<iframe src="/imports/excel" id="home_frame">

</iframe>